productpage:
  namespace: student9-bookinfo-uat
  image: ghcr.io/kuraigi/itkmitl-bookinfo-productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student9/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  REVIEWS_HOSTNAME: http://bookinfo-uat-reviews:8082
  RATINGS_HOSTNAME: http://bookinfo-uat-ratings:8080
  DETAILS_HOSTNAME: http://bookinfo-uat-details:8081